name: babycoin-build

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      CCACHE_COMPRESS: 1
      CCACHE_TEMPDIR: C:\Users\runneradmin\.ccache-temp
      CCACHE_DIR: C:\Users\runneradmin\.ccache
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: actions/cache@v2
      with:
        path: C:\Users\runneradmin\.ccache
        key: ccache-windows-build-${{ github.sha }}
        restore-keys: ccache-windows-build-
    - uses: eine/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-libusb mingw-w64-x86_64-libtool binutils git automake autoconf patch mingw-w64-x86_64-ccache
    - name: boost
      run: pacman --noconfirm -U https://mirrors.huaweicloud.com/msys2/mingw/x86_64/mingw-w64-x86_64-boost-1.62.0-1-any.pkg.tar.xz
    - name: build
      run: |
        ccache --max-size=150M
        make release-static-win -j 4
    - name: Upload windows artifacts
      uses: actions/upload-artifact@master
      with:
        name: windows
        path: 'build/**/**/babycoin*'

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: remove bundled boost
      run: sudo rm -rf /usr/local/share/boost
    - name: update apt
      run: sudo apt update
    - name: install Babycoin dependencies
      run: sudo apt -y install build-essential cmake libboost-all-dev miniupnpc libunbound-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libzmq3-dev libsodium-dev libhidapi-dev libnorm-dev libusb-1.0-0-dev libpgm-dev
    - name: build
      run: make release -j 4
    - name: Upload linux artifacts
      uses: actions/upload-artifact@master
      with:
        name: linux
        path: 'build/**/**/babycoin*'

  build-ubuntu-depends:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: update apt
      run: sudo apt update
    - name: install Babycoin dependencies
      run: sudo apt -y install build-essential cmake libboost-all-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libsodium-dev libhidapi-dev libusb-1.0-0-dev gperf libreadline-dev
    - name: build
      run: make depends target=x86_64-linux-gnu -j 4
    - name: Upload linux artifacts
      uses: actions/upload-artifact@master
      with:
        name: linux-static
        path: 'build/x86_64-linux-gnu/release/bin/babycoin*'

  build-dpends-compat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: update apt
      run: sudo apt update
    - name: install Babycoin dependencies
      run: sudo apt -y install build-essential cmake libboost-all-dev miniupnpc libunbound-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libzmq3-dev libsodium-dev libhidapi-dev libnorm-dev libusb-1.0-0-dev libpgm-dev gperf libreadline-dev
    - name: build
      run: make depends-compat target=x86_64-linux-gnu -j 4
    - name: Upload linux artifacts
      uses: actions/upload-artifact@master
      with:
        name: linux-compat
        path: 'build/x86_64-linux-gnu-compat/release/bin/babycoin*'
